
logger:
  dir: /tmp/unstableSK3
  limit: 10000000

tasks:
  t1:
    unit_time: 0.8
    batch_size: 9
    deficit: 100
  t2:
    unit_time: 0.1
    batch_size: 1
  t3:
    unit_time: 0.8
    batch_size: 9
  t4:
    unit_time: 0.1
    batch_size: 1

machines:
  m1:
    - t1
    - t4
  m2:
    - t2
    - t3

demands:
  - supplier: t1
    quantity: 1
    destination: t2
  - supplier: t2
    quantity: 1
    interval: 1
  - supplier: t3
    quantity: 1
    destination: t4
  - supplier: t4
    quantity: 1
    interval: 1

